name: ${name}
description: ${description}
version: ${version}
authors: [${author}]
main: ${mainClass}
website: ${url}
depend: [ProtocolLib]

api-version: 1.13

commands:
  mirrorskull:
    aliases: [mskull]
    permission: mirrorskull.command
    usage: /<command>